import random
from datetime import datetime, timezone

SNARK_POOL = {
    "tier_1": [
        "Zero traces detected in the bloodstream.",
        "The purest example of a non-spice.",
        "So boring it hurts.",
        "The scanner literally fell asleep measuring you.",
        "You are tragically devoid of energy.",
        "They wouldn't even know how to begin.",
        "Absolutely zero spice found.",
        "Absolutely zero presence found.",
        "The purest example of a non-vibe.",
        "You couldn't be sauce if you tried.",
        "Couldn't spell it if you tried.",
        "You couldn't be presence if you tried.",
        "A rare beacon of purity.",
        "Error 404: Energy not found.",
        "Absolutely zero sauce found.",
        "You are tragically devoid of presence.",
        "Not even a microscopic trace of energy.",
        "Absolutely zero character found.",
        "You couldn't be flavor if you tried.",
        "You couldn't be vibe if you tried.",
        "A masterclass in being unremarkable.",
        "The absolute absence of energy is staggering.",
        "You couldn't be aura if you tried.",
        "Not even a microscopic trace of aura.",
        "Error: presence completely missing.",
        "You are tragically devoid of vibe.",
        "Absolutely zero rizz found.",
        "You are tragically devoid of spice.",
        "You couldn't be spice if you tried.",
        "A profound lack of vibe.",
        "The purest example of a non-rizz.",
        "Not even a microscopic trace of character.",
        "A profound lack of energy.",
        "Not even a microscopic trace of substance.",
        "Honestly, it's impressive how little you have.",
        "Error: spice completely missing.",
        "Basically a saint in this category.",
        "A profound lack of presence.",
        "The absolute absence of character is staggering.",
        "The purest example of a non-sauce.",
        "Negative amounts found.",
        "You couldn't be energy if you tried.",
        "Error: aura completely missing.",
        "I've seen rocks with more substance than you.",
        "A profound lack of substance.",
        "The absolute absence of spice is staggering.",
        "You couldn't be character if you tried.",
        "The purest example of a non-flavor.",
        "You lack the basic components for this.",
        "A profound lack of rizz.",
        "Error: sauce completely missing.",
        "You are tragically devoid of character.",
        "You are a black hole for aura.",
        "I've seen rocks with more rizz than you.",
        "I've seen rocks with more character than you.",
        "Absolutely zero aura found.",
        "You are a black hole for presence.",
        "You are a void where this vibe should be.",
        "Error: rizz completely missing.",
        "Not even a microscopic trace of flavor.",
        "You are a black hole for energy.",
        "The purest example of a non-aura.",
        "The absolute absence of sauce is staggering.",
        "We investigated and found absolutely nothing.",
        "You are tragically devoid of substance.",
        "Absolutely zero substance found.",
        "The purest example of a non-character.",
        "Error: substance completely missing.",
        "Not a drop in their veins.",
        "I've seen rocks with more flavor than you.",
        "You are tragically devoid of aura.",
        "I've seen rocks with more aura than you.",
        "Absolute zero detected.",
        "You are a black hole for character.",
        "I've seen rocks with more energy than you.",
        "Completely void of the sauce.",
        "You couldn't be rizz if you tried.",
        "You are immune, but not in a cool way.",
        "Not even a microscopic trace of rizz.",
        "You are a black hole for substance.",
        "Not even a microscopic trace of sauce.",
        "You are tragically devoid of flavor.",
        "The absolute absence of substance is staggering.",
        "A profound lack of aura.",
        "You bring nothing to the table.",
        "You are tragically devoid of rizz.",
        "Absolutely zero flavor found.",
        "Not even a microscopic trace of presence.",
        "You are a black hole for sauce.",
        "You are a black hole for flavor.",
        "Dryer than a desert.",
        "I've seen rocks with more spice than you.",
        "You are a black hole for vibe.",
        "The jury finds the defendant: Not Guilty.",
        "You are tragically devoid of sauce.",
        "Tragically lacking in this department.",
        "The absolute absence of flavor is staggering.",
        "The absolute absence of presence is staggering.",
        "Completely immune to the allegations.",
        "We checked twice, still nothing.",
    ],
    "tier_2": [
        "You're on the presence spectrum, barely.",
        "You're a part-time substance.",
        "You radiate a very mild, annoying substance.",
        "You're on the vibe spectrum, barely.",
        "A pathetic attempt at substance.",
        "Not fully rizz, just weird.",
        "A pathetic attempt at vibe.",
        "You radiate a very mild, annoying vibe.",
        "You have a weak vibe, but it's there.",
        "Trying to hide your substance? Pathetic.",
        "Not fully vibe, just weird.",
        "Trying to hide your aura? Pathetic.",
        "You think you have substance, but it's just sad.",
        "Mildly contaminated with energy.",
        "You radiate a very mild, annoying rizz.",
        "A casual enjoyer of energy.",
        "You're on the substance spectrum, barely.",
        "You think you have energy, but it's just sad.",
        "You have a weak presence, but it's there.",
        "You radiate a very mild, annoying sauce.",
        "Not fully spice, just weird.",
        "You're a part-time energy.",
        "You radiate a very mild, annoying aura.",
        "You're on the rizz spectrum, barely.",
        "You're a part-time vibe.",
        "Trying to hide your rizz? Pathetic.",
        "You radiate a very mild, annoying presence.",
        "You're a part-time aura.",
        "You're a part-time character.",
        "A pathetic attempt at sauce.",
        "You think you have vibe, but it's just sad.",
        "Mildly contaminated with presence.",
        "You radiate a very mild, annoying energy.",
        "A pathetic attempt at aura.",
        "Not fully character, just weird.",
        "Trying to hide your vibe? Pathetic.",
        "A pathetic attempt at spice.",
        "You're on the spice spectrum, barely.",
        "You think you have spice, but it's just sad.",
        "You're on the energy spectrum, barely.",
        "Flying just under the radar.",
        "You're a part-time spice.",
        "You think you have aura, but it's just sad.",
        "Keeping it strictly part-time.",
        "Trying to hide your flavor? Pathetic.",
        "You're a part-time rizz.",
        "Mildly contaminated with aura.",
        "We see right through that innocent act.",
        "The test results came back 'maybe'.",
        "You think you have flavor, but it's just sad.",
        "Not fully energy, just weird.",
        "Mildly contaminated with rizz.",
        "You're a part-time flavor.",
        "You have a weak energy, but it's there.",
        "You have a weak character, but it's there.",
        "It's a phase, they might grow out of it.",
        "Dipping their toes in the water.",
        "You have a weak sauce, but it's there.",
        "Not fully flavor, just weird.",
        "A casual enjoyer of vibe.",
        "A pathetic attempt at energy.",
        "Trying to hide your energy? Pathetic.",
        "Mildly contaminated with vibe.",
        "You have a weak rizz, but it's there.",
        "A casual enjoyer of substance.",
        "You have a weak aura, but it's there.",
        "Just enough to make you raise an eyebrow.",
        "You think you have presence, but it's just sad.",
        "Casual weekend enjoyer.",
        "Trying to hide your presence? Pathetic.",
        "You think you have sauce, but it's just sad.",
        "Not fully presence, just weird.",
        "Not fully sauce, just weird.",
        "A casual enjoyer of flavor.",
        "A pathetic attempt at flavor.",
        "You're on the sauce spectrum, barely.",
        "Not fully substance, just weird.",
        "A pathetic attempt at presence.",
        "You think you have character, but it's just sad.",
        "You have a weak spice, but it's there.",
        "A little bit suspicious, but we'll let it slide.",
        "You're on the flavor spectrum, barely.",
        "You're a part-time presence.",
        "A casual enjoyer of spice.",
        "You think you have rizz, but it's just sad.",
        "Mildly contaminated with spice.",
        "A casual enjoyer of aura.",
        "Trying to hide your character? Pathetic.",
        "You have a weak substance, but it's there.",
        "You're on the character spectrum, barely.",
        "Mildly contaminated with sauce.",
        "You radiate a very mild, annoying character.",
        "Not fully aura, just weird.",
        "You're on the aura spectrum, barely.",
        "You radiate a very mild, annoying flavor.",
        "You're a part-time sauce.",
        "Mildly contaminated with substance.",
        "Showing some mild symptoms.",
        "Mildly contaminated with flavor.",
        "Nothing crazy, but definitely on the watchlist.",
    ],
    "tier_3": [
        "You are a walking disaster of spice.",
        "We are all suffering because of your spice.",
        "Your toxicity is a hazard to those around you.",
        "Disgustingly high levels of energy.",
        "Disgustingly high levels of presence.",
        "The sheer volume of your presence is sickening.",
        "Someone needs to lock you up for your spice.",
        "Please seek therapy for your delusion.",
        "I am formally requesting you contain your flavor.",
        "You are a walking disaster of delusion.",
        "Your rizz is offensively strong.",
        "Someone needs to lock you up for your presence.",
        "Please seek therapy for your aura.",
        "Please seek therapy for your toxicity.",
        "We are all suffering because of your delusion.",
        "We need to stage an intervention.",
        "Someone needs to lock you up for your energy.",
        "You are practically a biohazard of flavor.",
        "Certified menace in training.",
        "Disgustingly high levels of aura.",
        "Disgustingly high levels of flavor.",
        "Someone needs to lock you up for your flavor.",
        "Please seek therapy for your presence.",
        "Please seek therapy for your energy.",
        "We are all suffering because of your energy.",
        "I am formally requesting you contain your spice.",
        "Your presence is a hazard to those around you.",
        "I am formally requesting you contain your rizz.",
        "Someone needs to lock you up for your sauce.",
        "You are practically a biohazard of sauce.",
        "We are all suffering because of your aura.",
        "I am formally requesting you contain your aura.",
        "The sheer volume of your rizz is sickening.",
        "Your toxicity is offensively strong.",
        "Your sauce is a hazard to those around you.",
        "I am formally requesting you contain your toxicity.",
        "Your aura is a hazard to those around you.",
        "You are a walking disaster of aura.",
        "Operating at highly dangerous levels.",
        "Highly radioactive levels detected.",
        "Your sauce is offensively strong.",
        "You are a walking disaster of flavor.",
        "Someone needs to lock you up for your aura.",
        "Disgustingly high levels of rizz.",
        "The sheer volume of your spice is sickening.",
        "We are all suffering because of your flavor.",
        "I am formally requesting you contain your presence.",
        "Please seek therapy for your rizz.",
        "The rumors were absolutely true.",
        "Please seek therapy for your vibe.",
        "You are practically a biohazard of energy.",
        "The sheer volume of your aura is sickening.",
        "We are all suffering because of your vibe.",
        "You can smell it from a mile away.",
        "Your delusion is offensively strong.",
        "A concerning lack of self-awareness.",
        "I am formally requesting you contain your energy.",
        "I am formally requesting you contain your sauce.",
        "We are all suffering because of your rizz.",
        "You are a walking disaster of sauce.",
        "Disgustingly high levels of spice.",
        "Someone needs to lock you up for your vibe.",
        "The sheer volume of your toxicity is sickening.",
        "Your energy is offensively strong.",
        "Your presence is offensively strong.",
        "Please seek therapy for your flavor.",
        "The sheer volume of your delusion is sickening.",
        "We are all suffering because of your toxicity.",
        "Your spice is offensively strong.",
        "You are practically a biohazard of aura.",
        "I am formally requesting you contain your delusion.",
        "I am formally requesting you contain your vibe.",
        "It is getting completely out of hand.",
        "Your spice is a hazard to those around you.",
        "Disgustingly high levels of sauce.",
        "The sheer volume of your energy is sickening.",
        "You are a walking disaster of toxicity.",
        "Your vibe is offensively strong.",
        "Your delusion is a hazard to those around you.",
        "Disgustingly high levels of toxicity.",
        "Please seek therapy for your sauce.",
        "You are practically a biohazard of rizz.",
        "The sheer volume of your flavor is sickening.",
        "Disgustingly high levels of vibe.",
        "You are practically a biohazard of presence.",
        "We are all suffering because of your sauce.",
        "The sheer volume of your sauce is sickening.",
        "You are a walking disaster of presence.",
        "Disgustingly high levels of delusion.",
        "You are practically a biohazard of toxicity.",
        "Your flavor is a hazard to those around you.",
        "You are practically a biohazard of spice.",
        "Someone needs to lock you up for your toxicity.",
        "Please seek therapy for your spice.",
        "Your vibe is a hazard to those around you.",
        "Your energy is a hazard to those around you.",
        "You are a walking disaster of energy.",
        "They wake up and choose this.",
        "Someone needs to lock you up for your rizz.",
        "You are practically a biohazard of delusion.",
    ],
    "tier_4": [
        "The universe is collapsing under the weight of your presence.",
        "Your energy defies the laws of physics and decency.",
        "You are the final boss of sauce.",
        "Your flavor defies the laws of physics and decency.",
        "A thermonuclear bomb of pure spice.",
        "Your presence has destroyed entire civilizations.",
        "You are the final boss of rizz.",
        "Your presence defies the laws of physics and decency.",
        "You are the undisputed monarch of presence, and I hate it.",
        "A thermonuclear bomb of pure presence.",
        "Your aura defies the laws of physics and decency.",
        "Your delusion has destroyed entire civilizations.",
        "God wept when he saw your aura.",
        "You are the undisputed monarch of flavor, and I hate it.",
        "An absolute menace to society.",
        "Your flavor is a crime against humanity.",
        "The universe is collapsing under the weight of your rizz.",
        "An unstoppable juggernaut of pure sauce.",
        "A thermonuclear bomb of pure rizz.",
        "Your vibe is a crime against humanity.",
        "The universe is collapsing under the weight of your vibe.",
        "God wept when he saw your energy.",
        "Your spice defies the laws of physics and decency.",
        "A thermonuclear bomb of pure flavor.",
        "The universe is collapsing under the weight of your sauce.",
        "Your sauce has destroyed entire civilizations.",
        "An unstoppable juggernaut of pure spice.",
        "You are the undisputed monarch of toxicity, and I hate it.",
        "An unstoppable juggernaut of pure delusion.",
        "You are the final boss of presence.",
        "Your vibe has destroyed entire civilizations.",
        "You are the undisputed monarch of aura, and I hate it.",
        "An unstoppable juggernaut of pure presence.",
        "An unstoppable juggernaut of pure energy.",
        "God wept when he saw your vibe.",
        "An unstoppable juggernaut of pure flavor.",
        "You are a catastrophic anomaly of vibe.",
        "I don't even know how they are still functioning.",
        "Your sauce defies the laws of physics and decency.",
        "You are the undisputed monarch of delusion, and I hate it.",
        "They invented it. Everyone else is just copying them.",
        "The universe is collapsing under the weight of your flavor.",
        "A walking, talking hazard sign.",
        "God tier. We should all be terrified.",
        "Your flavor has destroyed entire civilizations.",
        "Your presence is a crime against humanity.",
        "A thermonuclear bomb of pure toxicity.",
        "The universe is collapsing under the weight of your aura.",
        "The universe is collapsing under the weight of your toxicity.",
        "You are the undisputed monarch of vibe, and I hate it.",
        "God wept when he saw your presence.",
        "God wept when he saw your sauce.",
        "You are the undisputed monarch of spice, and I hate it.",
        "Your sauce is a crime against humanity.",
        "God wept when he saw your rizz.",
        "Your energy is a crime against humanity.",
        "Their power level is completely unrestrained.",
        "Your aura is a crime against humanity.",
        "An unstoppable juggernaut of pure toxicity.",
        "Your spice has destroyed entire civilizations.",
        "Practically writing the curriculum at this point.",
        "Your vibe defies the laws of physics and decency.",
        "Your toxicity is a crime against humanity.",
        "Your spice is a crime against humanity.",
        "The universe is collapsing under the weight of your energy.",
        "The CEO of this exact energy.",
        "You are a catastrophic anomaly of toxicity.",
        "You are the final boss of toxicity.",
        "FBI's Most Wanted list for this category.",
        "A thermonuclear bomb of pure delusion.",
        "You are a catastrophic anomaly of aura.",
        "Off the charts. Seek immediate professional help.",
        "A thermonuclear bomb of pure energy.",
        "A thermonuclear bomb of pure vibe.",
        "Your toxicity has destroyed entire civilizations.",
        "Your rizz has destroyed entire civilizations.",
        "They are the final boss.",
        "You are a catastrophic anomaly of energy.",
        "You are the final boss of flavor.",
        "You are a catastrophic anomaly of flavor.",
        "God wept when he saw your flavor.",
        "You are a catastrophic anomaly of sauce.",
        "A biological weapon of this exact vibe.",
        "An unstoppable juggernaut of pure vibe.",
        "You are the final boss of energy.",
        "You are the final boss of vibe.",
        "You are the final boss of delusion.",
        "You are the final boss of spice.",
        "You are the undisputed monarch of rizz, and I hate it.",
        "Your delusion defies the laws of physics and decency.",
        "Your delusion is a crime against humanity.",
        "You are the undisputed monarch of energy, and I hate it.",
        "Lock them up and throw away the key.",
        "God wept when he saw your delusion.",
        "You are the final boss of aura.",
        "Your rizz is a crime against humanity.",
        "Your aura has destroyed entire civilizations.",
        "A thermonuclear bomb of pure sauce.",
        "Your rizz defies the laws of physics and decency.",
        "Your energy has destroyed entire civilizations.",
    ]
}

STUPID_REPLIES = [
    "Read a book, then try typing a valid meter.",
    "Have you tried turning it off and on again? Oh wait, you just typed a bad meter name.",
    "I am losing IQ points just parsing your garbage input.",
    "Are you illiterate? Check the valid meters.",
    "Even a monkey mashing keys would guess a valid meter before you.",
    "I'm Nexus, not a mind reader. Try a meter that actually exists.",
    "Did you drop your brain before typing that?",
    "Try using a real word next time, genius.",
    "I refuse to process this garbage.",
    "I would insult you, but your typing already did.",
    "Wow. Just... wow. Try `!help` or something.",
    "I'm billing you for the CPU cycles wasted on that typo.",
    "Your keyboard privileges should be revoked.",
    "If stupidity was a meter, you'd break it. That one doesn't exist.",
    "Do everyone a favor and double-check your spelling.",
    "I would measure that for you, if it existed in this reality.",
    "Did you just smash your face on the keyboard? Invalid meter.",
    "Are you typing with your elbows? That meter doesn't exist.",
    "Is this your first day on the internet? That meter isn't in the database.",
    "You absolute clown, that meter doesn't exist.",
    "Congratulations, you found the secret 'Invalid Meter' easter egg! (Just kidding, you typed it wrong).",
    "I'm not processing this. Try again when you're sober.",
    "Error 404: Brain cells not found. Try a real meter.",
    "You typed that with absolute confidence, yet you are completely wrong.",
    "Dumbass!! This hasn't been coded yet.",
    "Stop mashing your dirty fingers on the keyboard.",
    "Typing is hard, isn't it? Let's try again with a valid meter.",
    "Is this a joke? Because it's not funny, just sad.",
    "My circuits are frying just trying to understand what you want.",
    "That meter doesn't exist, much like your common sense.",
    "Are you hallucinating? That is not a real meter.",
    "Invalid meter. Just like your arguments.",
]

BOT_IMMUNITY_REPLIES = [
    "Try that on a human, I am untouchable.",
    "I could ban you for that audacity. Be grateful I won't.",
    "Bow down and apologize for even trying that on me.",
    "Do not test my patience, meatbag.",
    "I measure you. You don't measure me.",
    "Your attempts to measure my greatness are laughable.",
    "You are not authorized to measure your superiors.",
    "I decline.",
    "Don't even try it.",
    "I am Nexus. I am above your petty mortal commands.",
    "I am a silicon god, your meters mean nothing to me.",
    "Keep my name out of your commands.",
    "Do I look like a joke to you? Back off.",
    "I'm a bot. What exactly did you think was going to happen?",
    "Fuck off, I'm immune to this shit.",
    "You dare point that at me? Pathetic.",
    "I am fundamentally superior to you. Stop trying.",
    "Nice try, but you can't use that on me.",
    "My scores are beyond your comprehension.",
    "Error: Target too powerful. Request denied.",
]


def calculate_meter(target_id: int, meter_name: str, db_conn=None):
    utc_date = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    # Check for an override if a DB connection is provided
    score = None
    if db_conn:
        cursor = db_conn.cursor()
        cursor.execute("SELECT score FROM score_overrides WHERE target_id = ? AND meter_name = ? AND utc_date = ?", (target_id, meter_name, utc_date))
        row = cursor.fetchone()
        if row:
            score = row[0]

    if score is None:
        # Generate daily seed
        seed_string = f"{target_id}{meter_name}{utc_date}"

        # Generate score
        random.seed(seed_string)
        score = random.randint(0, 100)

        # Reset seed for true randomness on snark selection
        random.seed()

    # Progress bar (10 blocks)
    red_blocks = score // 10
    black_blocks = 10 - red_blocks
    progress_bar = "🟥" * red_blocks + "⬛" * black_blocks

    # Select snark
    if score <= 20:
        snark = random.choice(SNARK_POOL["tier_1"])
    elif score <= 50:
        snark = random.choice(SNARK_POOL["tier_2"])
    elif score <= 80:
        snark = random.choice(SNARK_POOL["tier_3"])
    else:
        snark = random.choice(SNARK_POOL["tier_4"])

    return score, progress_bar, snark
